### ISSUE TITLE
Bug report - get_fastccd_images 

### ISSUE THREAD

**Issue by vivekthampy** [NSLS-II-CSX/csxtools#38]
@stuwilkins The program crashes if the background scan headers have events with different number of images. The crashing function is get_images_to_4D. 

https://gist.github.com/vivekthampy/71d110d899f68a61150a

One solution that works for me is using the the function below instead of get_images_to_4D.

```python
def convert_to_3D(images):
    if isinstance(images, np.ndarray):
        if images.ndim == 3 or images.ndim == 2:
            return images
        elif images.ndim == 4:
            shape = images.shape
            return np.reshape(images, (shape[0]*shape[1], shape[2], shape[3]))
    else:
        ims = images[0]
        for im in images[1:]:
            ims = np.vstack((ims, im))
        return ims
```

**Comment by stuwilkins** [comment]
Why would you do that?

On Mar 2, 2016, at 12:57 AM, vivekthampy <notifications@github.com<mailto:notifications@github.com>> wrote:


@stuwilkins<https://github.com/stuwilkins> The program crashes if the background scan headers have events with different number of images. The crashing function is get_images_to_4D.

https://gist.github.com/vivekthampy/71d110d899f68a61150a

One solution that works for me is using the the function below instead of get_images_to_4D.

def convert_to_3D(images):
    if isinstance(images, np.ndarray):
        if images.ndim == 3 or images.ndim == 2:
            return images
        elif images.ndim == 4:
            shape = images.shape
            return np.reshape(images, (shape[0]*shape[1], shape[2], shape[3]))
    else:
        ims = images[0]
        for im in images[1:]:
            ims = np.vstack((ims, im))
        return ims

**Comment by stuwilkins** [comment]
Despite not being the normal CSX workflow, I have fixed this now. This is tagged as v0.1.8. Once it is built I will put it on the jupyter hub for all users. @vivekthampy can you test again? I ran this through your scans and it seems to work.
